version: '3.7'

services:
    api-admin:
        image: asia.gcr.io/emerald-diagram-352601/mainproject/admin:0.0.3
        platform: linux/x86_64
        # Dockerfile 설정
        build:
            # Dockerfile의 위치
            context: .

        container_name: codecamp-mainproject-api-admin

        # Container Port 연결
        #   - host:container
        ports:
            - 80:8081

        # Volume Mount
        #   - host:container
        volumes:
            - ./.env.prod:/app/.env

        # 환경 변수 설정
        env_file: .env.prod

        # 재시작 설정
        restart: always
